### PR TITLE
feat: implement string adapater

### PR DESCRIPTION
**Pull request by Gabriel-403**

### CODE REVIEW

**Review by calebfaruki — CHANGES_REQUESTED** [review]
Newly implemented methods should have corresponding tests.

* getPolicy
* addPolicy
* removePolicy
* addPolicies
* removePolicies

**Comment by Zxilly** [comment]
@Gabriel-403 plz uncomment thoses unit tests with TODO

**Review by nodece — CHANGES_REQUESTED** [review]

**Comment by nodece** [comment]
@Gabriel-403 @Zxilly  We should use array instead string policy, so like `[ ["p","alice","data","read"]]`.

**Comment by hsluoyz** [comment]
@Gabriel-403 plz reply.

**Comment by Gabriel-403** [comment]
> @Gabriel-403 @Zxilly We should use array instead string policy, so like `[ ["p","alice","data","read"]]`.

ok，woking on this and many code need try catch to catch issue，i do more  enhangce in these days

**Pull request merged**
