### PR TITLE
Create react supported parts for casbinjs.

### PR DESCRIPTION
**Pull request by Wsteth**
I'm already finished with the core functions of react components except for the test, build, and package.
There are the things I want to do is refactor casbin.js into casbinjs-core. In this, all functions will be closer to the casbin style.

### Todo list:
- Extract casbinjs-react's enforcer into casbinjs-core.
- The casbinjs-core will be the simple node-casbin that removes all the async operation.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@kingiw plz review.

**Comment by Zxilly** [comment]
consider make this a separate repo?

**Comment by hsluoyz** [comment]
@Wsteth made a new repo: https://github.com/casbin-js/react-authz

**Comment by hsluoyz** [comment]
Hi @Wsteth , could you move the code in this PR to our new repo for React? https://github.com/casbin-js/react-authz

**Comment by Wsteth** [comment]
Hi, @hsluoyz,
I'm already committed, pls reviews.

**Pull request closed without merging**
